### PR TITLE
base_change_form.html compatible with django 1.8

### PR DESCRIPTION
**Pull request by bashu**

### CODE REVIEW

**Comment by bashu** [comment]
manually tested with 1.5.12, 1.6.11, 1.7.7 and 1.8

**Comment by vdboor** [comment]
thanks for looking into this!

Are you sure this is also working on Django 1.5? The `add_preserved_filters` is not present in that version.

**Comment by bashu** [comment]
tested with 1.5.12

**Comment by vdboor** [comment]
ok, cool!

**Pull request merged**
