### PR TITLE
added multilingual ``textfile`` page type

### PR DESCRIPTION
**Pull request by bashu**
Hey,

I will fix related https://github.com/edoburu/django-fluent-pages/issues/63 later...

### CODE REVIEW

**Comment by bashu** [comment]
@vdboor can you review this one?

**Comment by vdboor** [comment]
Hi! Yes, I can! I just returned from my holidays.

A few things:
* Could you make sure the Django 1.7 migrations also have a nice name set? Instead of the `auto_..` you can reuse the names that the south migrations have.
* Does it make sense to make the `content_type` translatable too? After all, won't you expect the same file type in all places?

**Comment by bashu** [comment]
@vdboor check this...

**Comment by bashu** [comment]
closed via @f593f8bc91a428da6a3240420b177f641a98348d

**Pull request closed without merging**
